# Generated by Django 2.2.7 on 2020-04-18 01:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0102_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scratch_codes',
            field=judge.models.profile.EncryptedNullCharField(help_text='32 character base32-encoded key for TOTP', max_length=32, null=True, validators=[django.core.validators.RegexValidator('^$|^[A-Z2-7]{32}$', 'TOTP key must be empty or base32')], verbose_name='Scratch Codes'),
        ),
    ]
